id = "lama"
name = "Lama"
description = "Lama syntax highlighting"
version = "0.0.1"
schema_version = 1
authors = [
  "Vasily Fedorov <vasek.fedorov@gmail.com>",
]
repository = "https://github.com/sovesti/zed-lama"

[grammars.lama]
repository = "https://github.com/sovesti/tree-sitter-lama"
commit = "4aa578c53a4081440068f130185053250b449e59"
